### ISSUE TITLE
Function 'set_mute' not working

### ISSUE THREAD

**Issue by stefan747** [RoonLabs/node-roon-api-volume-control#1]
Hi,

Function 'set_mute' is not working with the latest version of Roon 1.4 (306).
The 'req' object now contains the 'on'/'off' value for mute in **req.body.mode**, but the function written here is trying to access it under **req.body.action**.

Fix can be done in two ways:
1/ fix Roon to pass the value in req.body.action
Then no update is needed on this function
2/ update the 'set_mute' function to use req.body.mode

Thanks,
Stefan

**Comment by bcoburn3** [comment]
This should be fixed in commit 87b6885
