### ISSUE TITLE
Destroy does not release the device in the extension

### ISSUE THREAD

**Issue by maru-sama** [RoonLabs/node-roon-api-volume-control#2]
https://github.com/RoonLabs/node-roon-api-volume-control/blob/87b6885bc5370a5b79d39869b2810d6dc332f486/lib.js#L42

When destroy is called the local callback is not removed correctly. The key used here should be

`delete(this._objs[o.state.control_key]);`

Issue #3 is related to this as well.

**Comment by bcoburn3** [comment]
I believe this to be fixed in commit 73ce294

**Comment by maru-sama** [comment]
I can confirm that this change fixes the issue.
