### ISSUE TITLE
How to implement volume control which supports only volumeUp/Down

### ISSUE THREAD

**Issue by ChristianRiedl** [RoonLabs/node-roon-api-volume-control#5]
I want to implement a volume control for a device which supports only volumeUp / Down.
I guess volume_type is the place where I can define it. As there is no documentation I was searching in samples and found only 'number' or 'db". 

How can I implement a volume control with "volumeUp" and "volumeDown" ?

**Comment by bcoburn3** [comment]
You should be able to pass "incremental" as the "volume_type".

Then your extension should get "set_volume" requests that look like this:
```                    
{
  "control_key"="12345",
  "mode"="relative",
  "value"=1.0
}
```
where "value" is the magnitude of the volume change requested.

Let me know if any of this doesn't work.

**Comment by ChristianRiedl** [comment]
Thanks, it works !!
